import { styled } from '..'
export const SingleContainer = styled('article', {
  p: {
    marginBottom: '1rem',
  },
  h1: {
    color: '$blue900',
    marginBottom: '2rem',
    fontSize: '2rem',
    fontWeight: 700,
    textAlign: 'center',
    display: 'inline-block',
    width: '100%',
  },
  img: {
    display: 'block',
    margin: '0 auto',
  },
  h2: {
    color: '$blue500',
    marginBottom: '1.5rem',
    fontSize: '2rem',
    fontWeight: 700,
    textAlign: 'center',
    display: 'inline-block',
    width: '100%',
  },
  h3: {
    color: '$blue500',
    marginBottom: '1.2rem',
    fontSize: '2rem',
    fontWeight: 700,
    textAlign: 'center',
    display: 'inline-block',
    width: '100%',
  },
  '.info_block': {
    marginTop: '1rem',
    '.info': { fontWeight: 700 },
    '.popular': { color: '$cot' },
    '.dev': { color: '$dev' },
    '.project': { color: 'project' },
  },
  '.img-title': {
    display: 'block',
    margin: '2rem auto',
    textAlign: 'center',
  },
  ul: {
    margin: '2rem',
    li: {
      paddingBottom: '2rem',
      marginLeft: '1rem',
      fontSize: '1rem',
      color: '$gray800',
      listStyle: 'square',
    },
  },
  '.content-post': {
    marginTop: '2rem',
    p: {
      paddingBottom: '1rem',
      marginLeft: '1rem',
      fontSize: '1rem',
      color: '$gray800',
      listStyle: 'square',
      margin: 0,
    },
    a: {
      color: '$blue500',
      fontWeight: 700,
      textDecoration: 'underline',
    },
  },
  pre: {
    display: 'block',
    overflowY: 'scroll',
    fontFamily: 'monospace',
    fontWeight: 400,
    textAlign: 'left',
    lineHeight: '1.6em',
    whiteSpace: 'pre',
    padding: '1em 2%',
    marginTop: '1em',
    marginRight: '5%',
    marginBottom: '1em',
    marginLeft: '0',
    border: 'solid 2px #ccc',
    borderRadius: '0.25em',
    backgroundColor: '#202020',
    color: '#fff',
  },
})
