import {
  CallSection,
  ContentCallSection,
  TerminalSection,
} from '@/styles/pages/home'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CallSection>
        <ContentCallSection>
          <h1>
            Hello, I am <br />
            <span>&#123;Arlen Resende&#125;</span>
            <br />a full-stack developer
          </h1>
          <p>
            &#123; ... With almost 10 years of experience in technologies such
            as Node.js, React, PHP, and Liquid. Throughout my career, I have had
            the opportunity to work on challenging and complex projects, which
            has allowed me to acquire strong skills in building scalable and
            high-performance web applications.&#125;
          </p>
        </ContentCallSection>
        <TerminalSection>
          <div className="terminal-window">
            <div className="terminal-header">
              <div className="terminal-button green"></div>
              <div className="terminal-button yellow"></div>
              <div className="terminal-button red"></div>
            </div>
            <div className="terminal-body">
              <div className="prompt">
                <div>
                  <span className="title">
                    &#x276F; ArlenResende.currentLocation
                  </span>
                  <span className="content">
                    &#x22;Resende Costa, Minas Gerais - Brazil&#x22;
                  </span>
                </div>
                <div>
                  <span className="title">
                    &#x276F; ArlenResende.contactInfo
                  </span>
                  <span className="content">
                    &#x22;arlenaraujo12@gmail.com&#x22;
                  </span>
                </div>
                <div>
                  <span className="title">&#x276F; ArlenResende.resume</span>
                  <span className="content">
                    &#x22;
                    <a href="" target="_blank">
                      arlenresende.pdf
                    </a>
                    &#x22;
                  </span>
                </div>
                <div>
                  <span className="title">&#x276F; ArlenResende.interests</span>
                  <span className="content">
                    [&#x22;Football Soccer&#x22;,&#x22; Design&#x22;,&#x22;
                    Guitar Player&#x22;]
                  </span>
                </div>
                <div>
                  <span className="title">&#x276F; ArlenResende.skills</span>
                  <span className="content">
                    [&#x22;JavaScript&#x22;, &#x22;React&#x22;, &#x22;React
                    native&#x22;, &#x22;NextJs&#x22;, &#x22;Node&#x22;,
                    &#x22;PHP&#x22;, &#x22;Liquid&#x22;,
                    &#x22;HTML&#x22;,&#x22;Css&#x22;,&#x22;Git&#x22;]
                  </span>
                </div>
                <div>
                  <span className="title">&#x276F;</span>
                </div>
              </div>
            </div>
          </div>
        </TerminalSection>
      </CallSection>
    </>
  )
}
